fix: Update Dockerfile.macos to include testing

diff --git a/.github/dockerimages/Dockerfile.macos b/.github/dockerimages/Dockerfile.macos
--- a/.github/dockerimages/Dockerfile.macos
+++ b/.github/dockerimages/Dockerfile.macos
@@ -31,17 +31,14 @@ RUN pip3 install -e . --break-system-packages
 # Run PyInstaller to create the standalone executable
 RUN pyinstaller --onefile --name taf -y taf/tools/cli/taf.py
 
-# Set user to root to move file
-USER root
-
 # Make the executable runnable
 RUN chmod +x dist/taf
 
+# Verify the standalone executable
+RUN ./dist/taf --help | grep "TAF Command Line Interface" || { echo "Error: Expected text not found in the executable output"; exit 1; }
+
 # Create the target directory and move the executable
 RUN mkdir -p /usr/src/app/taf/dist && mv dist/taf /usr/src/app/taf/dist/
-
-# Verify the location of the moved executable
-RUN find /usr/src/app/taf/dist -name taf -type f -exec echo "Full path of moved executable: {}" \;
 
 # Set the entry point to the executable
 ENTRYPOINT ["/usr/src/app/taf/dist/taf"]
