devops: define supported python versions using variables

diff --git a/.github/workflows/ci.yml b/.github/workflows/ci.yml
--- a/.github/workflows/ci.yml
+++ b/.github/workflows/ci.yml
@@ -7,18 +7,35 @@ on:
   release:
     types: [created]
 
+env:
+  VERSIONS: "['3.8', '3.9', '3.10', '3.11', '3.12']"
+  LAST_VERSION: '3.12'
+
 jobs:
+
+  set_python_versions:
+    runs-on: ubuntu-latest
+    outputs:
+      all_versions: ${{ steps.step1.outputs.matrix }}
+      last_version: ${{ steps.step1.outputs.last_version }}
+    steps:
+      - name: Set versions
+        id: step1
+        run: |
+          echo "matrix=${{env.VERSIONS}}" >> $GITHUB_OUTPUT
+          echo "last_version=${{env.LAST_VERSION}}" >> $GITHUB_OUTPUT
 
   run_tests:
     runs-on: ubuntu-latest
+    needs: set_python_versions
     strategy:
       matrix:
-        python-version: ["3.8", "3.9", "3.10", "3.11", "3.12"]
+        python-version: ${{ fromJSON(needs.set_python_versions.outputs.all_versions) }}
     steps:
       - uses: actions/checkout@v4
 
       - name: Set up Python ${{ matrix.python-version }}
-        uses: actions/setup-python@v4
+        uses: actions/setup-python@v5
         with:
           python-version: ${{ matrix.python-version }}
 
@@ -46,23 +63,18 @@ jobs:
 
   build_and_upload_wheel:
     runs-on: ubuntu-latest
-    needs: run_tests
+    needs: [set_python_versions, run_tests]
     if: github.event_name == 'release'
 
     steps:
       - name: Checkout code
         uses: actions/checkout@v4
 
-      - name: Set up Python ${{ matrix.python-version }}
-        uses: actions/setup-python@v4
-        with:
-          python-version: ${{ matrix.python-version }}
-
       - name: Set up Python
-        uses: actions/setup-python@v4
+        uses: actions/setup-python@v5
         with:
           # build it on the minimum version
-          python-version: '3.8'
+          python-version: ${{ fromJSON(needs.set_python_versions.outputs.all_versions)[0] }}
 
       - name: Upgrade pip
         run: |
@@ -94,7 +106,9 @@ jobs:
 
 
   build-and-test-executables:
-    needs: build_and_upload_wheel
+    needs: [set_python_versions, run_tests]
+    if: github.event_name == 'release'
+
     strategy:
       matrix:
         os: [ubuntu-latest, windows-latest, macos-latest]
@@ -110,10 +124,10 @@ jobs:
         run: echo "${{ github.event.release.upload_url  }}"
 
       - name: Set up Python
-        uses: actions/setup-python@v4
+        uses: actions/setup-python@v5
         with:
           # the newest python that we support
-          python-version: '3.12'
+          python-version: ${{ needs.set_python_versions.outputs.last_version }}
 
       - name: Upgrade pip windows
         if: matrix.os == 'windows-latest'
@@ -150,51 +164,39 @@ jobs:
       - name: Build and test standalone executable (Linux)
         if: matrix.os == 'ubuntu-latest'
         run: |
-          pyinstaller --onefile --hidden-import=yubikey_manager --name taf -y taf/tools/cli/taf.py
-          chmod +x dist/taf
-          ./dist/taf --help | grep "TAF Command Line Interface" || { echo "Error: Expected text not found in the executable output"; exit 1; }
+          pyinstaller --onefile --hidden-import=yubikey_manager --name taf-linux -y taf/tools/cli/taf.py
+          chmod +x dist/taf-linux
+          ./dist/taf-linux --help | grep "TAF Command Line Interface" || { echo "Error: Expected text not found in the executable output"; exit 1; }
 
       - name: Build and test standalone executable (Windows)
         if: matrix.os == 'windows-latest'
         run: |
-          pyinstaller --onefile --hidden-import=yubikey_manager  --name taf.exe -y taf/tools/cli/taf.py
-          ./dist/taf.exe --help | Select-String "TAF Command Line Interface" -quiet
+          pyinstaller --onefile --hidden-import=yubikey_manager  --name taf-windows.exe -y taf/tools/cli/taf.py
+          ./dist/taf-windows.exe --help | Select-String "TAF Command Line Interface" -quiet
 
       - name: Build and test standalone executable (macOS)
         if: matrix.os == 'macos-latest'
         run: |
-          pyinstaller --onefile --hidden-import=yubikey_manager  --name taf -y taf/tools/cli/taf.py
-          ./dist/taf --help | grep "TAF Command Line Interface" || { echo "Error: Expected text not found in the executable output"; exit 1; }
+          pyinstaller --onefile --hidden-import=yubikey_manager  --name taf-macos -y taf/tools/cli/taf.py
+          ./dist/taf-macos --help | grep "TAF Command Line Interface" || { echo "Error: Expected text not found in the executable output"; exit 1; }
 
       - name: Upload standalone executable (Linux)
         if: matrix.os == 'ubuntu-latest'
-        uses: actions/upload-release-asset@v1
-        with:
-          upload_url: ${{ github.event.release.upload_url }}
-          asset_path: dist/taf
-          asset_name: taf-linux
-          asset_content_type: application/x-executable
+        run: |
+          gh release upload ${{github.event.release.tag_name}} dist/taf-linux
         env:
           GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
 
       - name: Upload standalone executable (Windows)
         if: matrix.os == 'windows-latest'
-        uses: actions/upload-release-asset@v1
-        with:
-          upload_url: ${{ github.event.release.upload_url }}
-          asset_path: dist/taf.exe
-          asset_name: taf-windows.exe
-          asset_content_type: application/octet-stream
+        run: |
+          gh release upload ${{github.event.release.tag_name}} dist/taf-windows.exe
         env:
           GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
 
       - name: Upload standalone executable (macOS)
         if: matrix.os == 'macos-latest'
-        uses: actions/upload-release-asset@v1
-        with:
-          upload_url: ${{ github.event.release.upload_url }}
-          asset_path: dist/taf
-          asset_name: taf-macos
-          asset_content_type: application/octet-stream
+        run: |
+          gh release upload ${{github.event.release.tag_name}} dist/taf-macos
         env:
           GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
